spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB

mybatis-plus:
  type-aliases-package: com.liuzw.*.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty